#database 연동 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: jsw0101151!
  thymeleaf:
    prefix: classpath:templates/
    #    suffix: .html
    suffix: .jsp
    cache: false
server:
  port: 9000
#  thymeleaf:
#    prefix: classpath:templates/
#    #    suffix: .html
#    suffix: .jsp
#    cache: false
#  # Spring Data JPA 설정
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL57Dialect
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL57Dialect
#        format_sql: true
#        use_sql_comments: true
logging:
  level:
    org.hibernate.SQL: debug
